param([string]$ProjectRoot='')
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)}
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force
function Assert([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
$contextJson=& (Join-Path $ProjectRoot 'scripts\validate_context_samples.ps1') -ProjectRoot $ProjectRoot;$context=$contextJson|ConvertFrom-Json;Assert ($context.Status-eq'PASS'-and$context.Rows-eq12-and$context.UniqueMatchIDs-eq12-and$context.DataStatus-eq'CONTEXT_ONLY_NOT_TRAINING') 'World Cup context sample validation failed'
$requirementsJson=& (Join-Path $ProjectRoot 'scripts\audit_project_requirements.ps1') -ProjectRoot $ProjectRoot;$requirements=$requirementsJson|ConvertFrom-Json;Assert ($requirements.Status-eq'PASS'-and$requirements.RuleCount-eq71-and$requirements.ProductionModels-eq0) 'Project requirements audit failed'
$versionControlJson=& (Join-Path $ProjectRoot 'scripts\audit_version_control.ps1') -ProjectRoot $ProjectRoot;$versionControl=$versionControlJson|ConvertFrom-Json;Assert ($versionControl.Status-in@('GIT_COMMIT_CHAIN','HASH_CHAIN_LEDGER','UNAVAILABLE')) 'Version-control audit returned invalid status';Assert (($versionControl.Status-eq'GIT_COMMIT_CHAIN')-or($versionControl.Status-eq'HASH_CHAIN_LEDGER')) 'No verifiable version-control chain is available'
$archiveAuditJson=& (Join-Path $ProjectRoot 'scripts\audit_source_archive.ps1') -ArchiveRoot (Join-Path $ProjectRoot 'data\source_archive') -OutputRoot (Join-Path $ProjectRoot 'data\quality');$archiveAudit=$archiveAuditJson|ConvertFrom-Json;Assert ($archiveAudit.Status-eq'PASS'-and$archiveAudit.FileCount-gt0-and$archiveAudit.UniqueHashes-gt0) 'Source archive manifest audit failed'

$p=Get-DixonColesPrediction 1.5 1.0 -0.12
Assert ([Math]::Abs(($p.HomeProbability+$p.DrawProbability+$p.AwayProbability)-1.0)-lt 1e-10) 'Poisson probabilities do not sum to one'
Assert ($p.HomeProbability-ge0-and$p.DrawProbability-ge0-and$p.AwayProbability-ge0) 'Negative Poisson probability'
$market=Get-DeVigProbabilities 1.53 4.33 6.00
Assert ([Math]::Abs(($market.HomeProbability+$market.DrawProbability+$market.AwayProbability)-1.0)-lt 1e-10) 'Market probabilities do not sum to one'
Assert ($market.ReturnRate-gt0-and$market.ReturnRate-lt1) 'Invalid return rate'
$handicap=Get-DixonColesPrediction 1.5 1.0 -0.12 8 -1
Assert ([Math]::Abs(($handicap.HandicapHomeProbability+$handicap.HandicapDrawProbability+$handicap.HandicapAwayProbability)-1.0)-lt 1e-10) 'Handicap probabilities do not sum to one'
Assert ($handicap.HandicapHomeProbability-lt$p.HomeProbability) 'Negative home handicap must reduce home-win probability'
$handicapModule=Join-Path $ProjectRoot 'src\HandicapModel.psm1';Import-Module $handicapModule -Force
$jczqMargin=Get-JczqHandicapPrediction 1.65 0.85 -1
$marginTotal=$jczqMargin.HomeWin1Probability+$jczqMargin.HomeWin2Probability+$jczqMargin.HomeWin3PlusProbability+$jczqMargin.DrawProbability+$jczqMargin.AwayWinProbability
$jczqTotal=$jczqMargin.HandicapWinProbability+$jczqMargin.HandicapDrawProbability+$jczqMargin.HandicapLossProbability
Assert ([Math]::Abs($marginTotal-1.0)-lt 1e-10) 'JCZQ goal-margin distribution does not sum to one'
Assert ([Math]::Abs($jczqTotal-1.0)-lt 1e-10) 'JCZQ handicap mapping does not sum to one'
Assert ($jczqMargin.HomeWin2Probability-gt0) 'JCZQ goal-margin distribution returned no two-goal-win probability'
$q1=Get-AsianSettlement 1 1 -0.25 HOME 2.0;$q2=Get-AsianSettlement 1 0 -0.75 HOME 2.0;$q3=Get-AsianSettlement 1 1 0.25 HOME 2.0;$q4=Get-AsianSettlement 1 1 -0.25 AWAY 2.0
Assert ($q1.Outcome-eq'HALF_LOSS'-and[Math]::Abs($q1.NetReturn+0.5)-lt1e-10) 'Asian -0.25 draw settlement failed';Assert ($q2.Outcome-eq'HALF_WIN'-and[Math]::Abs($q2.NetReturn-0.5)-lt1e-10) 'Asian -0.75 one-goal win settlement failed';Assert ($q3.Outcome-eq'HALF_WIN') 'Asian +0.25 draw settlement failed';Assert ($q4.Outcome-eq'HALF_WIN') 'Asian away-side inversion failed'
$titanAtert=Convert-TitanHandicapToHomeLine '-0/0.5';Assert ($titanAtert.HomeLine-eq0.25-and$titanAtert.FavouredSide-eq'AWAY') 'Titan -0/0.5 must normalize to home +0.25 / away favourite';$titanSutjeska=Convert-TitanHandicapToHomeLine '-0.5/1';Assert ($titanSutjeska.HomeLine-eq0.75-and$titanSutjeska.FavouredSide-eq'AWAY') 'Titan -0.5/1 must normalize to home +0.75 / away favourite';$titanEgnatia=Convert-TitanHandicapToHomeLine '0.5/1';Assert ($titanEgnatia.HomeLine-eq-0.75-and$titanEgnatia.FavouredSide-eq'HOME') 'Titan 0.5/1 must normalize to home -0.75 / home favourite';$titanAtertCheck=Test-TitanHandicapDirection '-0/0.5' 2.60 2.32;Assert $titanAtertCheck.Passed 'Titan Atert direction should agree with 1X2';$titanSutjeskaCheck=Test-TitanHandicapDirection '-0.5/1' 4.60 1.54;Assert $titanSutjeskaCheck.Passed 'Titan Sutjeska direction should agree with 1X2';$titanContradiction=Test-TitanHandicapDirection '-0.5/1' 1.54 4.60;Assert (-not$titanContradiction.Passed-and$titanContradiction.Reason-like'CONTRADICTION*') 'Titan contradiction must stop direction output'

$matchesPath=Join-Path $ProjectRoot 'data\standardized\matches.csv';$oddsPath=Join-Path $ProjectRoot 'data\standardized\odds_1x2_close.csv'
$matches=@(Import-Csv -LiteralPath $matchesPath -Encoding UTF8);$ids=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$mismatch=0;foreach($r in $matches){Assert ($ids.Add($r.MatchID)) "Duplicate MatchID $($r.MatchID)";$h=[int]$r.HomeGoals;$a=[int]$r.AwayGoals;$expected=if($h-gt$a){'H'}elseif($h-eq$a){'D'}else{'A'};if($r.Result-ne$expected){$mismatch++}}
Assert ($matches.Count-eq60512) 'Unexpected standardized match count';Assert ($mismatch-eq0) 'Score/result mismatch'
$orphan=0;$oddsCount=0;Import-Csv -LiteralPath $oddsPath -Encoding UTF8|ForEach-Object{$oddsCount++;if(-not$ids.Contains($_.MatchID)){$orphan++}}
Assert ($oddsCount-eq185694) 'Unexpected odds count';Assert ($orphan-eq0) 'Orphan odds rows'
$allMatches=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'data\standardized\matches_all.csv') -Encoding UTF8);$allIds=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($r in $allMatches){Assert ($allIds.Add($r.MatchID)) "Duplicate unified MatchID $($r.MatchID)"}
Assert ($allMatches.Count-eq83659) 'Unexpected unified match count';$extendedMarkets=0;$extendedOrphans=0;Import-Csv -LiteralPath (Join-Path $ProjectRoot 'data\standardized\markets_extended.csv') -Encoding UTF8|ForEach-Object{$extendedMarkets++;if(-not$allIds.Contains($_.MatchID)){$extendedOrphans++}}
Assert ($extendedMarkets-eq138695) 'Unexpected extended market count';Assert ($extendedOrphans-eq0) 'Orphan extended market rows'

$summary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\baseline-v1\summary.json')|ConvertFrom-Json
$predictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\baseline-v1\predictions.csv') -Encoding UTF8)
Assert ($predictions.Count-eq13105) 'Unexpected backtest prediction count'
$predictionIds=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($r in $predictions){Assert ($predictionIds.Add($r.MatchID)) "Duplicate prediction $($r.MatchID)";Assert ($ids.Contains($r.MatchID)) "Unknown prediction MatchID $($r.MatchID)"}
$bra=$summary.Leagues|Where-Object{$_.LeagueCode-eq'BRA'};$jpn=$summary.Leagues|Where-Object{$_.LeagueCode-eq'JPN'};$swe=$summary.Leagues|Where-Object{$_.LeagueCode-eq'SWE'}
Assert (-not $bra.GatePassed) 'BRA gate must fail';Assert ($jpn.GatePassed) 'JPN gate must pass';Assert ($swe.GatePassed) 'SWE gate must pass'
$euroSummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\europe-market-v1\summary.json')|ConvertFrom-Json;$euroPredictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\europe-market-v1\predictions.csv') -Encoding UTF8)
Assert ($euroSummary.Leagues.Count-eq13) 'Unexpected European league count';Assert ($euroPredictions.Count-eq22068) 'Unexpected European prediction count';Assert (@($euroSummary.Leagues|Where-Object{$_.GatePassed}).Count-eq11) 'Unexpected European gate pass count';Assert (@($euroSummary.Leagues|Where-Object{-not$_.GatePassed}).Count-eq2) 'Unexpected European gate fail count'
$asianSummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\asian-v1\summary.json')|ConvertFrom-Json;$asianPredictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\asian-v1\predictions.csv') -Encoding UTF8);$asianBets=($asianSummary.Leagues|Measure-Object Bets -Sum).Sum;$asianProfit=($asianSummary.Leagues|Measure-Object Profit -Sum).Sum
Assert ($asianSummary.Leagues.Count-eq13) 'Unexpected Asian league count';Assert ($asianPredictions.Count-eq16904) 'Unexpected Asian prediction count';Assert ($asianBets-eq$asianPredictions.Count) 'Asian bet count mismatch';Assert (@($asianSummary.Leagues|Where-Object{$_.GatePassed}).Count-eq0) 'Asian model must have zero gate passes';Assert ([Math]::Abs($asianProfit-($asianPredictions|Measure-Object NetReturn -Sum).Sum)-lt1e-8) 'Asian profit does not reconcile'
$totalsSummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\totals-v1\summary.json')|ConvertFrom-Json;$totalsPredictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\totals-v1\predictions.csv') -Encoding UTF8);$totalsBets=($totalsSummary.Leagues|Measure-Object Bets -Sum).Sum;$totalsProfit=($totalsSummary.Leagues|Measure-Object Profit -Sum).Sum
Assert ($totalsSummary.Leagues.Count-eq13) 'Unexpected totals league count';Assert ($totalsPredictions.Count-eq15253) 'Unexpected totals prediction count';Assert ($totalsBets-eq$totalsPredictions.Count) 'Totals bet count mismatch';Assert (@($totalsSummary.Leagues|Where-Object{$_.GatePassed}).Count-eq0) 'Totals model must have zero gate passes';Assert ([Math]::Abs($totalsProfit-($totalsPredictions|Measure-Object NetReturn -Sum).Sum)-lt1e-8) 'Totals profit does not reconcile'
$movementSummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\market-movement-v1\summary.json')|ConvertFrom-Json;$movementPredictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\market-movement-v1\predictions.csv') -Encoding UTF8);$movementSignals=($movementSummary.Leagues|Measure-Object Signals -Sum).Sum;$movementProfit=($movementSummary.Leagues|Measure-Object Profit -Sum).Sum
Assert ($movementSummary.Leagues.Count-eq13) 'Unexpected movement league count';Assert ($movementPredictions.Count-eq9480) 'Unexpected movement signal count';Assert ($movementSignals-eq$movementPredictions.Count) 'Movement signal count mismatch';Assert (@($movementSummary.Leagues|Where-Object{$_.GatePassed}).Count-eq0) 'Movement model must have zero gate passes';Assert ([Math]::Abs($movementProfit-($movementPredictions|Measure-Object NetReturn -Sum).Sum)-lt1e-8) 'Movement profit does not reconcile'
$scoreSummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\score-calibration-v1\summary.json')|ConvertFrom-Json;$scoreRows=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\score-calibration-v1\scores.csv') -Encoding UTF8)
Assert ($scoreRows.Count-eq26373) 'Unexpected score calibration count';Assert ($scoreSummary.GatePassed.AIScore) 'AI score calibration gate must pass';Assert ($scoreSummary.GatePassed.Confidence) 'Confidence gate must pass';Assert (-not$scoreSummary.GatePassed.Upset) 'Upset gate must fail';Assert ($scoreSummary.LeaguePassCounts.AIScore-eq13) 'AI score league consistency failed';Assert ($scoreSummary.LeaguePassCounts.Confidence-eq13) 'Confidence league consistency failed';Assert ($scoreSummary.LeaguePassCounts.Upset-eq5) 'Unexpected upset league pass count'
$kellySummary=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'backtests\euro-kelly-v1\summary.json')|ConvertFrom-Json;$kellyPredictions=@(Import-Csv -LiteralPath (Join-Path $ProjectRoot 'backtests\euro-kelly-v1\predictions.csv') -Encoding UTF8);$kellyBets=($kellySummary.Leagues|Measure-Object Bets -Sum).Sum;$kellyFlatProfit=($kellySummary.Leagues|Measure-Object FlatProfit -Sum).Sum;$kellyFinal=($kellySummary.Leagues|Measure-Object KellyFinalBankroll -Sum).Sum
Assert ($kellySummary.Leagues.Count-eq13) 'Unexpected Kelly league count';Assert ($kellyPredictions.Count-eq10362) 'Unexpected Kelly bet count';Assert ($kellyBets-eq$kellyPredictions.Count) 'Kelly bet count mismatch';Assert (@($kellySummary.Leagues|Where-Object{$_.GatePassed}).Count-eq0) 'Kelly model must have zero gate passes';Assert ([Math]::Abs($kellyFlatProfit-($kellyPredictions|Measure-Object FlatNetReturn -Sum).Sum)-lt1e-8) 'Kelly flat profit does not reconcile';Assert ([Math]::Abs(($kellyFinal-1300)-($kellyPredictions|Measure-Object KellyNetReturn -Sum).Sum)-lt1e-8) 'Kelly bankroll does not reconcile';Assert ([double](($kellyPredictions|Measure-Object StakeFraction -Minimum).Minimum)-gt0) 'Kelly stake fraction unexpectedly zero';Assert ([double](($kellyPredictions|Measure-Object StakeFraction -Maximum).Maximum)-le0.02) 'Kelly stake cap exceeded'
$analysisJson=& (Join-Path $ProjectRoot 'scripts\analyze.ps1') -LeagueCode SWE -HomeTeam Hacken -AwayTeam Hammarby -HomeOdds 2.4 -DrawOdds 3.5 -AwayOdds 2.8 -Handicap -1
$analysis=$analysisJson|ConvertFrom-Json;Assert (-not $analysis.FormalRecommendation) 'Research engine must not emit a formal recommendation';Assert ($analysis.HandicapWDL-eq'A') 'Handicap parameter was not applied'
$report=Get-Content -Raw -Encoding UTF8 $analysis.ReportPath;Assert ($report-notmatch '\{\{[A-Z_]+\}\}') 'Unresolved report placeholder';Assert (([regex]::Matches($report,'(?m)^## ')).Count-ge8) 'Required report sections are missing';Assert ($report.Contains('Home team home-only:')) 'Venue and head-to-head context missing from report';Assert ($report.Contains('FormalRecommendation')-eq$false) 'Internal JSON field leaked into report'
$fixtureJson=& (Join-Path $ProjectRoot 'scripts\register_fixture.ps1') -LeagueCode TEST -Season 2026 -MatchDate 2026-07-20 -HomeTeam Alpha -AwayTeam Beta -ValidateOnly;$fixture=$fixtureJson|ConvertFrom-Json;Assert ($fixture.MatchID-eq'FAI-e91b8c4262d37f01dbcb1498') 'Fixture MatchID is not deterministic'
$templateJson=& (Join-Path $ProjectRoot 'scripts\import_jczq.ps1') -InputPath (Join-Path $ProjectRoot 'data\templates\jczq_odds_template.csv') -ValidateOnly;$templateResult=$templateJson|ConvertFrom-Json;Assert ($templateResult.Status-eq'VALID_TEMPLATE'-and$templateResult.Rows-eq0) 'JCZQ template validation failed'
$evidenceJson=& (Join-Path $ProjectRoot 'scripts\register_jczq_evidence.ps1') -EvidencePath (Join-Path $ProjectRoot 'tests\fixtures\jczq_valid_test.csv') -CapturedAt '2026-07-15T12:00:00+08:00' -EvidenceType OFFICIAL_EXPORT -ValidateOnly;$evidence=$evidenceJson|ConvertFrom-Json;Assert ($evidence.Status-eq'VALID'-and$evidence.EvidenceID-like'JCZQ-EV-*'-and(-not$evidence.Written)) 'JCZQ evidence registration validation failed'
$jczqJson=& (Join-Path $ProjectRoot 'scripts\import_jczq.ps1') -InputPath (Join-Path $ProjectRoot 'tests\fixtures\jczq_valid_test.csv') -ValidateOnly -AllowTestSource;$jczq=$jczqJson|ConvertFrom-Json;Assert ($jczq.Status-eq'VALID'-and$jczq.Rows-eq3-and$jczq.Groups-eq1-and(-not$jczq.Written)) 'JCZQ test snapshot validation failed';$nonOfficialRejected=$false;try{& (Join-Path $ProjectRoot 'scripts\import_jczq.ps1') -InputPath (Join-Path $ProjectRoot 'tests\fixtures\jczq_valid_test.csv') -ValidateOnly|Out-Null}catch{$nonOfficialRejected=$true};Assert $nonOfficialRejected 'Non-official JCZQ source was not rejected';$evidenceRejected=$false;try{& (Join-Path $ProjectRoot 'scripts\import_jczq.ps1') -InputPath (Join-Path $ProjectRoot 'tests\fixtures\jczq_official_unregistered.csv') -ValidateOnly|Out-Null}catch{$evidenceRejected=$_.Exception.Message -like '*Unregistered evidence reference*'};Assert $evidenceRejected 'Official JCZQ odds without registered evidence were not rejected';$official=@(Import-Csv (Join-Path $ProjectRoot 'data\standardized\jczq_odds.csv') -Encoding UTF8);Assert ($official.Count-eq12) 'Unexpected official JCZQ odds row count';Assert (@($official|Where-Object {$_.MatchID-eq'FAI-e51b2e8d964c4242b11039ec'-and$_.SourceReference-eq'JCZQ-EV-F4C14C3202FD91434658'}).Count-eq6) 'Initial official JCZQ evidence linkage failed';Assert (@($official|Where-Object {$_.MatchID-eq'FAI-e51b2e8d964c4242b11039ec'-and$_.SourceReference-eq'JCZQ-EV-6E3AEDDA3E5F98583B3E'}).Count-eq6) 'Updated official JCZQ evidence linkage failed';$officialRows=$official.Count
$jczqReportJson=& (Join-Path $ProjectRoot 'scripts\analyze_jczq_snapshots.ps1') -MatchID 'FAI-e51b2e8d964c4242b11039ec' -ProjectRoot $ProjectRoot;$jczqReport=$jczqReportJson|ConvertFrom-Json;Assert ($jczqReport.Status-eq'PASS'-and$jczqReport.Snapshots-eq2-and(-not$jczqReport.FormalRecommendation)) 'JCZQ snapshot report generation failed';$jczqReportText=Get-Content -LiteralPath $jczqReport.ReportPath -Raw -Encoding UTF8;Assert ($jczqReportText-notmatch '\{\{[A-Z_]+\}\}') 'JCZQ snapshot report has unresolved placeholder';Assert ($jczqReportText.Contains('JCZQ-EV-6E3AEDDA3E5F98583B3E')) 'JCZQ snapshot report evidence missing'
$qualitySummaryPath=Join-Path $ProjectRoot 'data\quality\low_trust_history_summary.csv';Assert (Test-Path $qualitySummaryPath) 'Low-trust audit summary missing';$quality=@(Import-Csv $qualitySummaryPath -Encoding UTF8);$coreQuality=@($quality|Where-Object {$_.Dataset -eq 'match_history_core'});$intQuality=@($quality|Where-Object {$_.Dataset -eq 'international_matches'});$coreQualityCheck=(($coreQuality.Count -eq 1) -and ($coreQuality[0].Rows -eq '148375') -and ($coreQuality[0].Reviewable -eq '24370') -and ($coreQuality[0].Quarantined -eq '124005'));$intQualityCheck=(($intQuality.Count -eq 1) -and ($intQuality[0].Rows -eq '1673') -and ($intQuality[0].Reviewable -eq '0') -and ($intQuality[0].Quarantined -eq '1673'));Assert $coreQualityCheck 'Core low-trust audit counts changed';Assert $intQualityCheck 'International low-trust audit counts changed'
[pscustomobject]@{Status='PASS';BaseMatches=$matches.Count;UnifiedMatches=$allMatches.Count;UniqueUnifiedMatchIDs=$allIds.Count;Odds=$oddsCount;ExtendedMarkets=$extendedMarkets;BasePredictions=$predictions.Count;EuropeanPredictions=$euroPredictions.Count;AsianBets=$asianPredictions.Count;AsianProfit=[Math]::Round($asianProfit,3);AsianGatePasses=0;TotalsBets=$totalsPredictions.Count;TotalsProfit=[Math]::Round($totalsProfit,3);TotalsGatePasses=0;MovementSignals=$movementPredictions.Count;MovementProfit=[Math]::Round($movementProfit,3);MovementGatePasses=0;ScoreCalibrationRows=$scoreRows.Count;AIScoreGate=$scoreSummary.GatePassed.AIScore;ConfidenceGate=$scoreSummary.GatePassed.Confidence;UpsetGate=$scoreSummary.GatePassed.Upset;KellyBets=$kellyPredictions.Count;KellyFlatProfit=[Math]::Round($kellyFlatProfit,3);KellyFinalBankroll=[Math]::Round($kellyFinal,3);KellyGatePasses=0;OfficialJCZQRows=$officialRows;JCZQInterface='PASS';NonOfficialRejected=$nonOfficialRejected;OrphanOdds=$orphan;OrphanExtendedMarkets=$extendedOrphans;ResultMismatches=$mismatch;AutoReport='PASS';FormalRecommendation=$analysis.FormalRecommendation} | ConvertTo-Json
