param(
 [Parameter(Mandatory=$true)][string]$LeagueCode,
 [Parameter(Mandatory=$true)][string]$HomeTeam,
 [Parameter(Mandatory=$true)][string]$AwayTeam,
 [string]$CutoffDate='',
 [double]$HomeOdds=0,[double]$DrawOdds=0,[double]$AwayOdds=0,[ValidateSet('EUROPE','JCZQ')][string]$OddsSource='EUROPE',
 [int]$Handicap=999,
 [string]$ProjectRoot='',[int]$Window=10,[double]$HomeAdvantage=1.15,[double]$Rho=-0.12
)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)}
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force
$LeagueCode=$LeagueCode.Trim().ToUpperInvariant();if($CutoffDate-eq''){$CutoffDate=(Get-Date).ToString('yyyy-MM-dd')}
$validated=@('JPN','SWE','FD_B1','FD_D1','FD_E0','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SP1','FD_T1');$status=if($LeagueCode-in$validated){'validated'}else{'candidate'}
$matchesPath=Join-Path $ProjectRoot 'data\standardized\matches_all.csv';if(-not(Test-Path $matchesPath)){$matchesPath=Join-Path $ProjectRoot 'data\standardized\matches.csv'}
$matches=@(Import-Csv -LiteralPath $matchesPath -Encoding UTF8|Where-Object{$_.LeagueCode-eq$LeagueCode-and$_.MatchDate-ne''-and$_.MatchDate-lt$CutoffDate}|Sort-Object MatchDate,MatchTime,SourceRow)
if($matches.Count-eq0){throw "No dated historical matches for $LeagueCode before $CutoffDate"}
$homeRows=@($matches|Where-Object{$_.HomeTeam-eq$HomeTeam-or$_.AwayTeam-eq$HomeTeam}|Select-Object -Last $Window)
$awayRows=@($matches|Where-Object{$_.HomeTeam-eq$AwayTeam-or$_.AwayTeam-eq$AwayTeam}|Select-Object -Last $Window)
if($homeRows.Count-lt5-or$awayRows.Count-lt5){throw "Minimum history not met: $HomeTeam=$($homeRows.Count), $AwayTeam=$($awayRows.Count)"}
function TeamGF($row,$team){if($row.HomeTeam-eq$team){return [double]$row.HomeGoals}else{return [double]$row.AwayGoals}}
function TeamGA($row,$team){if($row.HomeTeam-eq$team){return [double]$row.AwayGoals}else{return [double]$row.HomeGoals}}
$hgf=($homeRows|ForEach-Object{TeamGF $_ $HomeTeam}|Measure-Object -Average).Average;$hga=($homeRows|ForEach-Object{TeamGA $_ $HomeTeam}|Measure-Object -Average).Average
$agf=($awayRows|ForEach-Object{TeamGF $_ $AwayTeam}|Measure-Object -Average).Average;$aga=($awayRows|ForEach-Object{TeamGA $_ $AwayTeam}|Measure-Object -Average).Average
$homeVenue=@($matches|Where-Object{$_.HomeTeam-eq$HomeTeam}|Select-Object -Last $Window);$awayVenue=@($matches|Where-Object{$_.AwayTeam-eq$AwayTeam}|Select-Object -Last $Window)
$h2h=@($matches|Where-Object{($_.HomeTeam-eq$HomeTeam-and$_.AwayTeam-eq$AwayTeam)-or($_.HomeTeam-eq$AwayTeam-and$_.AwayTeam-eq$HomeTeam)}|Select-Object -Last 5)
function Format-Record($rows,$team){if($rows.Count-eq0){return 'no sample'};$w=0;$d=0;$l=0;foreach($x in $rows){$gf=TeamGF $x $team;$ga=TeamGA $x $team;if($gf-gt$ga){$w++}elseif($gf-eq$ga){$d++}else{$l++}};return "$($rows.Count) matches, W-D-L $w-$d-$l, GF $([Math]::Round(($rows|ForEach-Object{TeamGF $_ $team}|Measure-Object -Average).Average,2)), GA $([Math]::Round(($rows|ForEach-Object{TeamGA $_ $team}|Measure-Object -Average).Average,2))"}
$h2hText=if($h2h.Count-eq0){'no prior same-league head-to-head in dated sample'}else{Format-Record $h2h $HomeTeam}
$contextText="Home team home-only: $(Format-Record $homeVenue $HomeTeam). Away team away-only: $(Format-Record $awayVenue $AwayTeam). Head-to-head from home-team perspective: $h2hText. Context is descriptive only and does not alter the backtested Poisson baseline."
$hasHandicap=$Handicap-ne999;$lh=(($hgf+$aga)/2.0)*$HomeAdvantage;$la=($agf+$hga)/2.0;$hc=if($hasHandicap){$Handicap}else{0};$p=Get-DixonColesPrediction $lh $la $Rho 8 $hc
$pairs=@(@('H',$p.HomeProbability),@('D',$p.DrawProbability),@('A',$p.AwayProbability))|Sort-Object {[double]$_[1]} -Descending;$top=[double]$pairs[0][1];$second=[double]$pairs[1][1]
$ai=[Math]::Round($top*100,1);$confidence=[Math]::Round([Math]::Min(100,($top-$second)*200),1);$fair=[Math]::Round(1.0/$top,2);$aiLabel=if($status-eq'validated'){"$ai/100 (validated display metric)"}else{"$ai/100 (experimental)"};$confidenceLabel=if($status-eq'validated'){"$confidence/100 (validated ranking metric)"}else{"$confidence/100 (experimental)"}
$market=$null;$marketPick='';$upset=$null;$upsetLabel='unavailable';$oddsText='No complete 1X2 odds supplied.';$returnText='Unavailable: complete odds are required.';$kellyText='Unavailable: complete odds are required.'
if($HomeOdds-gt1-and$DrawOdds-gt1-and$AwayOdds-gt1){$market=Get-DeVigProbabilities $HomeOdds $DrawOdds $AwayOdds;$marketPick=if($market.HomeProbability-ge$market.DrawProbability-and$market.HomeProbability-ge$market.AwayProbability){'H'}elseif($market.DrawProbability-ge$market.AwayProbability){'D'}else{'A'};$modelPick=$p.Prediction;$modelFavorite=if($marketPick-eq'H'){$p.HomeProbability}elseif($marketPick-eq'D'){$p.DrawProbability}else{$p.AwayProbability};$upset=[Math]::Round((1-$modelFavorite)*100,1);$upsetLabel="$upset/100 (candidate; failed calibration gate)";$sourceLabel=if($OddsSource-eq'JCZQ'){'China Sports Lottery SPF'}else{'European 1X2'};$oddsText="$sourceLabel input: $HomeOdds / $DrawOdds / $AwayOdds; de-vig probabilities: H=$([Math]::Round($market.HomeProbability*100,2))% D=$([Math]::Round($market.DrawProbability*100,2))% A=$([Math]::Round($market.AwayProbability*100,2))%; market favorite=$marketPick.";$returnText="$sourceLabel estimated return rate: $([Math]::Round($market.ReturnRate*100,2))%.";$ks=@();foreach($x in @(@('H',$p.HomeProbability,$HomeOdds),@('D',$p.DrawProbability,$DrawOdds),@('A',$p.AwayProbability,$AwayOdds))){$k=(([double]$x[1]*[double]$x[2])-1)/([double]$x[2]-1);$ks+="$($x[0])=$([Math]::Round($k,4))"};$kellyText='Model-implied Kelly fractions (candidate model failed ROI gate; not stake advice): '+($ks-join', ')}
$risk=@();$risk+='No production model is available; output is research-only.';if($status-ne'validated'){$risk+="Poisson baseline is not validated for $LeagueCode."};if($null-eq$market){$risk+='Missing complete 1X2 odds: return rate, value, Kelly and upset index are unavailable.'}else{$risk+='Upset index failed its cross-league calibration gate and remains candidate.'};if(-not$hasHandicap){$risk+='Missing handicap input: handicap WDL is unavailable.'}else{$risk+='Handicap result is model-derived only; no Asian/China Sports Lottery handicap price was supplied or backtested.'};$risk+='AI score and confidence passed calibration/ranking gates on validated leagues, but neither proves betting profitability.'
$recommendation=if($status-eq'validated'){"Research lean $($p.Prediction); no formal bet"}else{'NO BET - model not validated for this league'}
$handicapText=if($hasHandicap){"Home handicap ${hc}: H=$([Math]::Round($p.HandicapHomeProbability*100,1))%, D=$([Math]::Round($p.HandicapDrawProbability*100,1))%, A=$([Math]::Round($p.HandicapAwayProbability*100,1))%."}else{'Handicap analysis unavailable: no handicap supplied.'}
$handicapWdl=if($hasHandicap){$p.HandicapPrediction}else{'unavailable'};$topScores=($p.TopScores|ForEach-Object{"$($_.Score) $([Math]::Round($_.Probability*100,1))%"})-join'; '
$repl=[ordered]@{'{{GENERATED_AT}}'=(Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz');'{{CUTOFF}}'=$CutoffDate;'{{VERSION}}'=(Get-Content -Raw (Join-Path $ProjectRoot 'VERSION')).Trim();'{{MODEL_STATUS}}'="FootballAI-Poisson-Baseline 1.0.0 ($status)";'{{MATCH}}'="$HomeTeam vs $AwayTeam ($LeagueCode)";'{{RECOMMENDATION}}'=$recommendation;'{{RECOMMENDED_ODDS}}'="fair reference $fair; not a production recommendation";'{{AI_SCORE}}'=$aiLabel;'{{CONFIDENCE}}'=$confidenceLabel;'{{UPSET_INDEX}}'=$upsetLabel;'{{RESEARCH_NOTICE}}'='This report is research output, not a production betting recommendation.';'{{HOME_SAMPLE}}'=$homeRows.Count;'{{AWAY_SAMPLE}}'=$awayRows.Count;'{{WINDOW}}'=$Window;'{{LAMBDA_HOME}}'=[Math]::Round($p.HomeLambda,3);'{{LAMBDA_AWAY}}'=[Math]::Round($p.AwayLambda,3);'{{CONTEXT_ANALYSIS}}'=$contextText;'{{DATA_QUALITY}}'="historical results available; model status=$status";'{{ODDS_ANALYSIS}}'=$oddsText;'{{RETURN_ANALYSIS}}'=$returnText;'{{KELLY_ANALYSIS}}'=$kellyText;'{{PH}}'="$([Math]::Round($p.HomeProbability*100,2))%";'{{PD}}'="$([Math]::Round($p.DrawProbability*100,2))%";'{{PA}}'="$([Math]::Round($p.AwayProbability*100,2))%";'{{SCORE}}'="$($p.ScoreHome)-$($p.ScoreAway)";'{{TOP_SCORES}}'=$topScores;'{{UNDER25}}'="$([Math]::Round($p.Under25Probability*100,2))%";'{{OVER25}}'="$([Math]::Round($p.Over25Probability*100,2))%";'{{TOTAL_MODE}}'=$p.TotalGoalsMode;'{{HANDICAP_ANALYSIS}}'=$handicapText;'{{WDL}}'=$p.Prediction;'{{HANDICAP_WDL}}'=$handicapWdl;'{{TOTAL_SIDE}}'=if($p.Under25Probability-ge$p.Over25Probability){'Under 2.5'}else{'Over 2.5'};'{{RISK_SUMMARY}}'=($risk-join' ');'{{RISKS}}'=(($risk|ForEach-Object{'- '+$_})-join"`r`n");'{{DATA_HASH}}'=(Get-FileHash $matchesPath -Algorithm SHA256).Hash.ToLowerInvariant();'{{HOME_ADVANTAGE}}'=$HomeAdvantage;'{{RHO}}'=$Rho}
$report=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'docs\REPORT_RUNTIME_TEMPLATE.md');foreach($k in $repl.Keys){$report=$report.Replace($k,[string]$repl[$k])}
$outDir=Join-Path $ProjectRoot 'reports';New-Item -ItemType Directory -Force -Path $outDir|Out-Null;$safe=(($LeagueCode+'_'+$HomeTeam+'_'+$AwayTeam)-replace'[^A-Za-z0-9_-]','_');$path=Join-Path $outDir ($safe+'.md');$report|Set-Content -LiteralPath $path -Encoding UTF8
[pscustomobject]@{ReportPath=$path;LeagueCode=$LeagueCode;HomeTeam=$HomeTeam;AwayTeam=$AwayTeam;ModelStatus=$status;FormalRecommendation=$false;WDL=$p.Prediction;HandicapWDL=$handicapWdl;Score="$($p.ScoreHome)-$($p.ScoreAway)";TotalGoals=$p.TotalGoalsMode;UpsetIndex=$upset;AIScore=$ai;Confidence=$confidence;FairOdds=$fair;Risks=$risk}|ConvertTo-Json -Depth 5
