param([Parameter(Mandatory=$true)][string]$MatchID,[string]$ProjectRoot='',[string]$OutputPath='')
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)}
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force
$db=Join-Path $ProjectRoot 'data\standardized\jczq_odds.csv';if(-not(Test-Path -LiteralPath $db)){throw 'Official JCZQ odds database missing'}
$rows=@(Import-Csv -LiteralPath $db -Encoding UTF8|Where-Object{$_.MatchID -eq $MatchID});if($rows.Count -eq 0){throw "No official JCZQ odds for MatchID: $MatchID"}
$groups=@($rows|Where-Object{$_.Market -eq 'SPF'}|Group-Object SnapshotTime|Sort-Object {[datetimeoffset]$_.Name});if($groups.Count -eq 0){throw "No SPF snapshots for MatchID: $MatchID"}
function Read-Spf([object]$group){$m=@{};foreach($r in $group.Group){$m[$r.Selection]=[double]$r.Odds};if(($m.Keys.Count -ne 3) -or -not($m.ContainsKey('H') -and $m.ContainsKey('D') -and $m.ContainsKey('A'))){throw "Incomplete SPF snapshot: $($group.Name)"};$p=Get-DeVigProbabilities $m.H $m.D $m.A;return [pscustomobject]@{Time=[datetimeoffset]$group.Name;H=$m.H;D=$m.D;A=$m.A;PH=$p.HomeProbability;PD=$p.DrawProbability;PA=$p.AwayProbability;ReturnRate=$p.ReturnRate;Evidence=$group.Group[0].SourceReference}}
$initial=Read-Spf $groups[0];$latest=Read-Spf $groups[$groups.Count-1];$dh=($latest.PH-$initial.PH)*100;$dd=($latest.PD-$initial.PD)*100;$da=($latest.PA-$initial.PA)*100
<# Legacy RQSPF rendering below is retained as damaged-source evidence only.
$rq=@($rows|Where-Object{($_.Market -eq 'RQSPF') -and ($_.Handicap -eq '-1')}|Group-Object SnapshotTime|Sort-Object {[datetimeoffset]$_.Name});$rqText='无完整的官方让[-1]快照。'
if($rq.Count){$m=@{};foreach($r in $rq[$rq.Count-1].Group){$m[$r.Selection]=[double]$r.Odds};if($m.ContainsKey('H') -and $m.ContainsKey('D') -and $m.ContainsKey('A')){$rp=Get-DeVigProbabilities $m.H $m.D $m.A;$rqText=('最新让[-1]：胜 {0:N2} / 平 {1:N2} / 负 {2:N2}；去水概率 胜 {3:N2}% / 平 {4:N2}% / 负 {5:N2}%；返还率 {6:N2}%。' -f $m.H,$m.D,$m.A,($rp.HomeProbability*100),($rp.DrawProbability*100),($rp.AwayProbability*100),($rp.ReturnRate*100))}}
#>
$rq=@($rows|Where-Object{($_.Market -eq 'RQSPF') -and ($_.Handicap -eq '-1')}|Group-Object SnapshotTime|Sort-Object {[datetimeoffset]$_.Name})
$rqText='No complete official RQSPF -1 snapshot is available.'
if($rq.Count){$m=@{};foreach($r in $rq[$rq.Count-1].Group){$m[$r.Selection]=[double]$r.Odds};if($m.ContainsKey('H') -and $m.ContainsKey('D') -and $m.ContainsKey('A')){$rp=Get-DeVigProbabilities $m.H $m.D $m.A;$rqText=('Latest RQSPF -1: H {0:N2} / D {1:N2} / A {2:N2}; de-vig H {3:N2}% / D {4:N2}% / A {5:N2}%; return rate {6:N2}%.' -f $m.H,$m.D,$m.A,($rp.HomeProbability*100),($rp.DrawProbability*100),($rp.AwayProbability*100),($rp.ReturnRate*100))}}
$template=Join-Path $ProjectRoot 'docs\JCZQ_SNAPSHOT_TEMPLATE.md';$text=Get-Content -LiteralPath $template -Raw -Encoding UTF8
$tokens=[ordered]@{'@@MATCHID@@'=$MatchID;'@@COUNT@@'=$groups.Count;'@@INITIAL_TIME@@'=$initial.Time.ToString('yyyy-MM-dd HH:mm zzz');'@@LATEST_TIME@@'=$latest.Time.ToString('yyyy-MM-dd HH:mm zzz');'@@INITIAL_EVIDENCE@@'=$initial.Evidence;'@@LATEST_EVIDENCE@@'=$latest.Evidence;'@@IH@@'=$initial.H.ToString('N2');'@@ID@@'=$initial.D.ToString('N2');'@@IA@@'=$initial.A.ToString('N2');'@@LH@@'=$latest.H.ToString('N2');'@@LD@@'=$latest.D.ToString('N2');'@@LA@@'=$latest.A.ToString('N2');'@@IPH@@'=(($initial.PH*100).ToString('N2'));'@@IPD@@'=(($initial.PD*100).ToString('N2'));'@@IPA@@'=(($initial.PA*100).ToString('N2'));'@@LPH@@'=(($latest.PH*100).ToString('N2'));'@@LPD@@'=(($latest.PD*100).ToString('N2'));'@@LPA@@'=(($latest.PA*100).ToString('N2'));'@@DH@@'=$dh.ToString('+0.00;-0.00;0.00');'@@DD@@'=$dd.ToString('+0.00;-0.00;0.00');'@@DA@@'=$da.ToString('+0.00;-0.00;0.00');'@@IR@@'=(($initial.ReturnRate*100).ToString('N2'));'@@LR@@'=(($latest.ReturnRate*100).ToString('N2'));'@@RQ@@'=$rqText};foreach($key in $tokens.Keys){$text=$text.Replace($key,[string]$tokens[$key])}
if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath=Join-Path $ProjectRoot ('reports\JCZQ_'+$MatchID+'_snapshot.md')};$text|Set-Content -LiteralPath $OutputPath -Encoding UTF8
[pscustomobject]@{Status='PASS';MatchID=$MatchID;Snapshots=$groups.Count;LatestSnapshot=$latest.Time.ToString('o');LatestEvidence=$latest.Evidence;ReportPath=$OutputPath;FormalRecommendation=$false}|ConvertTo-Json
