param([string[]]$LeagueCodes=@('FD_B1','FD_D1','FD_E0','FD_E1','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SC1','FD_SP1','FD_T1'),[string]$ProjectRoot='',[double]$MinExpectedValue=0.03,[int]$Window=10,[int]$MinimumHistory=5,[double]$HomeAdvantage=1.15,[double]$Rho=-0.12)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$LeagueCodes=@($LeagueCodes|ForEach-Object{$_-split','}|ForEach-Object{$_.Trim().ToUpperInvariant()}|Where-Object{$_-ne''})
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force;$data=Join-Path $ProjectRoot 'data\standardized';$out=Join-Path $ProjectRoot 'backtests\totals-v1';New-Item -ItemType Directory -Force -Path $out|Out-Null
$markets=@{};Import-Csv (Join-Path $data 'markets_extended.csv') -Encoding UTF8|Where-Object{$_.Market-eq'TOTAL_CLOSE'-and$_.Line-eq'2.5'}|ForEach-Object{$markets[$_.MatchID]=$_}
$rowsAll=@(Import-Csv (Join-Path $data 'matches_all.csv') -Encoding UTF8|Where-Object{$_.LeagueCode-in$LeagueCodes}|Sort-Object LeagueCode,MatchDate,MatchTime,SourceRow);$preds=[Collections.Generic.List[object]]::new();$summaries=[Collections.Generic.List[object]]::new()
foreach($league in $LeagueCodes){$rows=@($rowsAll|Where-Object{$_.LeagueCode-eq$league});if($rows.Count-eq0){throw "No matches for $league"};$stats=@{};$returns=[Collections.Generic.List[double]]::new();$profit=0.0;$peak=0.0;$maxDrawdown=0.0;$eligible=0;$skipped=0;$overBets=0;$underBets=0;$wins=0;$losses=0
 foreach($r in $rows){$ht=$r.HomeTeam;$at=$r.AwayTeam;if(-not$stats.ContainsKey($ht)){$stats[$ht]=@{GF=[Collections.ArrayList]::new();GA=[Collections.ArrayList]::new()}};if(-not$stats.ContainsKey($at)){$stats[$at]=@{GF=[Collections.ArrayList]::new();GA=[Collections.ArrayList]::new()}};$hs=$stats[$ht];$as=$stats[$at]
  if($hs.GF.Count-ge$MinimumHistory-and$as.GF.Count-ge$MinimumHistory-and$markets.ContainsKey($r.MatchID)){$eligible++;$m=$markets[$r.MatchID];$lh=((Get-MeanLast $hs.GF $Window)+(Get-MeanLast $as.GA $Window))/2.0*$HomeAdvantage;$la=((Get-MeanLast $as.GF $Window)+(Get-MeanLast $hs.GA $Window))/2.0;$p=Get-DixonColesPrediction $lh $la $Rho;$overOdds=[double]$m.OverOdds;$underOdds=[double]$m.UnderOdds;$overEV=$p.Over25Probability*$overOdds-1.0;$underEV=$p.Under25Probability*$underOdds-1.0;$side=if($overEV-ge$underEV){'OVER'}else{'UNDER'};$best=if($side-eq'OVER'){$overEV}else{$underEV}
   if($best-ge$MinExpectedValue){$actualOver=(([int]$r.HomeGoals+[int]$r.AwayGoals)-gt2);$won=if($side-eq'OVER'){$actualOver}else{-not$actualOver};$odds=if($side-eq'OVER'){$overOdds}else{$underOdds};$net=if($won){$odds-1.0}else{-1.0};if($side-eq'OVER'){$overBets++}else{$underBets++};if($won){$wins++}else{$losses++};$returns.Add($net);$profit+=$net;if($profit-gt$peak){$peak=$profit};$dd=$peak-$profit;if($dd-gt$maxDrawdown){$maxDrawdown=$dd};$preds.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$league;MatchDate=$r.MatchDate;HomeTeam=$ht;AwayTeam=$at;HomeGoals=$r.HomeGoals;AwayGoals=$r.AwayGoals;LambdaH=$lh;LambdaA=$la;OverProbability=$p.Over25Probability;UnderProbability=$p.Under25Probability;OverOdds=$overOdds;UnderOdds=$underOdds;OverEV=$overEV;UnderEV=$underEV;SelectedSide=$side;SelectedEV=$best;Won=$won;NetReturn=$net;CumulativeProfit=$profit})}else{$skipped++}}
  [void]$hs.GF.Add([int]$r.HomeGoals);[void]$hs.GA.Add([int]$r.AwayGoals);[void]$as.GF.Add([int]$r.AwayGoals);[void]$as.GA.Add([int]$r.HomeGoals)}
 $n=$returns.Count;$roi=if($n){$profit/$n}else{0};$ss=0.0;foreach($x in $returns){$ss+=($x-$roi)*($x-$roi)};$se=if($n-gt1){[Math]::Sqrt(($ss/($n-1))/$n)}else{$null};$lower=if($null-ne$se){$roi-1.96*$se}else{$null};$pass=$n-ge500-and$roi-gt0-and$null-ne$lower-and$lower-gt0;$summaries.Add([pscustomobject]@{LeagueCode=$league;SourceMatches=$rows.Count;Eligible=$eligible;Bets=$n;SkippedByEV=$skipped;OverBets=$overBets;UnderBets=$underBets;Wins=$wins;Losses=$losses;Profit=$profit;ROI=$roi;ReturnStdError=$se;Lower95=$lower;MaxDrawdown=$maxDrawdown;GatePassed=$pass})}
$preds|Export-Csv (Join-Path $out 'predictions.csv') -NoTypeInformation -Encoding UTF8;$artifact=[ordered]@{Model='FootballAI-Totals-Baseline';Version='1.0.0-candidate';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');DataSha256=(Get-FileHash (Join-Path $data 'matches_all.csv') -Algorithm SHA256).Hash.ToLowerInvariant();MarketSha256=(Get-FileHash (Join-Path $data 'markets_extended.csv') -Algorithm SHA256).Hash.ToLowerInvariant();Protocol='docs/TOTALS_BACKTEST_PROTOCOL.md';Parameters=[ordered]@{Line=2.5;MinExpectedValue=$MinExpectedValue;Window=$Window;MinimumHistory=$MinimumHistory;HomeAdvantage=$HomeAdvantage;Rho=$Rho;Stake=1.0};Leagues=$summaries};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
