param([string]$ProjectRoot='',[double]$ModelWeight=0.25,[double]$MinimumExpectedValue=0.03,[double]$KellyFraction=0.25,[double]$MaxStakeFraction=0.02)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$out=Join-Path $ProjectRoot 'backtests\euro-kelly-v1';New-Item -ItemType Directory -Force -Path $out|Out-Null;$marketWeight=1-$ModelWeight
$validated=@('JPN','SWE','FD_B1','FD_D1','FD_E0','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SP1','FD_T1');$raw=@();$raw+=Import-Csv (Join-Path $ProjectRoot 'backtests\baseline-v1\predictions.csv') -Encoding UTF8;$raw+=Import-Csv (Join-Path $ProjectRoot 'backtests\europe-market-v1\predictions.csv') -Encoding UTF8
$odds=@{};Import-Csv (Join-Path $ProjectRoot 'data\standardized\odds_1x2_close.csv') -Encoding UTF8|Where-Object{$_.Provider-eq'MarketAverage'}|ForEach-Object{$odds[$_.MatchID]=$_};Import-Csv (Join-Path $ProjectRoot 'data\standardized\markets_extended.csv') -Encoding UTF8|Where-Object{$_.Market-eq'1X2_CLOSE'}|ForEach-Object{$odds[$_.MatchID]=$_}
$preds=[Collections.Generic.List[object]]::new();$summaries=[Collections.Generic.List[object]]::new()
foreach($league in $validated){$rows=@($raw|Where-Object{$_.LeagueCode-eq$league-and$_.MarketPH-ne''});$returns=[Collections.Generic.List[double]]::new();$profit=0.0;$peak=0.0;$maxDD=0.0;$bankroll=100.0;$bankPeak=100.0;$bankMaxDD=0.0;$eligible=0;$skipped=0;$sumReturnRate=0.0;$directions=@{H=0;D=0;A=0}
 foreach($r in $rows){if(-not$odds.ContainsKey($r.MatchID)){continue};$o=$odds[$r.MatchID];$oh=[double]$o.HomeOdds;$od=[double]$o.DrawOdds;$oa=[double]$o.AwayOdds;$rawSum=1/$oh+1/$od+1/$oa;$returnRate=1/$rawSum;$eligible++;$sumReturnRate+=$returnRate;$fh=$marketWeight*[double]$r.MarketPH+$ModelWeight*[double]$r.PH;$fd=$marketWeight*[double]$r.MarketPD+$ModelWeight*[double]$r.PD;$fa=$marketWeight*[double]$r.MarketPA+$ModelWeight*[double]$r.PA;$choices=@(@('H',$fh,$oh),@('D',$fd,$od),@('A',$fa,$oa))|ForEach-Object{[pscustomobject]@{Side=$_[0];Probability=[double]$_[1];Odds=[double]$_[2];EV=([double]$_[1]*[double]$_[2]-1)}}|Sort-Object EV -Descending;$c=$choices[0];if($c.EV-lt$MinimumExpectedValue){$skipped++;continue};$won=$c.Side-eq$r.Result;$net=if($won){$c.Odds-1}else{-1.0};$returns.Add($net);$profit+=$net;if($profit-gt$peak){$peak=$profit};$dd=$peak-$profit;if($dd-gt$maxDD){$maxDD=$dd};$fullKelly=[double]$c.EV/([double]$c.Odds-1.0);$quarterKelly=[double]$KellyFraction*$fullKelly;$stakeFraction=[Math]::Min([double]$MaxStakeFraction,[Math]::Max(0.0,[double]$quarterKelly));$stake=$bankroll*$stakeFraction;$bankNet=if($won){$stake*([double]$c.Odds-1.0)}else{-$stake};$bankroll+=$bankNet;if($bankroll-gt$bankPeak){$bankPeak=$bankroll};$bankDD=if($bankPeak-gt0){($bankPeak-$bankroll)/$bankPeak}else{1};if($bankDD-gt$bankMaxDD){$bankMaxDD=$bankDD};$directions[$c.Side]++
  $preds.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$league;Result=$r.Result;ModelPH=$r.PH;ModelPD=$r.PD;ModelPA=$r.PA;MarketPH=$r.MarketPH;MarketPD=$r.MarketPD;MarketPA=$r.MarketPA;FusedPH=$fh;FusedPD=$fd;FusedPA=$fa;HomeOdds=$oh;DrawOdds=$od;AwayOdds=$oa;ReturnRate=$returnRate;SelectedSide=$c.Side;SelectedProbability=$c.Probability;SelectedOdds=$c.Odds;SelectedEV=$c.EV;FullKelly=$fullKelly;StakeFraction=$stakeFraction;Stake=$stake;Won=$won;FlatNetReturn=$net;FlatCumulativeProfit=$profit;KellyNetReturn=$bankNet;Bankroll=$bankroll})}
 $n=$returns.Count;$roi=if($n){$profit/$n}else{0};$ss=0.0;foreach($x in $returns){$ss+=($x-$roi)*($x-$roi)};$se=if($n-gt1){[Math]::Sqrt(($ss/($n-1))/$n)}else{$null};$lower=if($null-ne$se){$roi-1.96*$se}else{$null};$pass=$n-ge500-and$roi-gt0-and$null-ne$lower-and$lower-gt0-and$bankroll-gt100-and$bankMaxDD-le0.25
 $summaries.Add([pscustomobject]@{LeagueCode=$league;SourcePredictions=$rows.Count;EligibleWithOdds=$eligible;Bets=$n;SkippedByEV=$skipped;HomeBets=$directions.H;DrawBets=$directions.D;AwayBets=$directions.A;AverageReturnRate=if($eligible){$sumReturnRate/$eligible}else{$null};FlatProfit=$profit;FlatROI=$roi;ReturnStdError=$se;Lower95=$lower;FlatMaxDrawdown=$maxDD;KellyFinalBankroll=$bankroll;KellyReturn=($bankroll/100-1);KellyMaxDrawdown=$bankMaxDD;GatePassed=$pass})}
$preds|Export-Csv (Join-Path $out 'predictions.csv') -NoTypeInformation -Encoding UTF8;$artifact=[ordered]@{Model='FootballAI-Euro-Fusion-Kelly';Version='1.0.0-candidate';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');Protocol='docs/EURO_KELLY_PROTOCOL.md';PredictionHashes=@{Baseline=(Get-FileHash (Join-Path $ProjectRoot 'backtests\baseline-v1\predictions.csv') -Algorithm SHA256).Hash.ToLowerInvariant();Europe=(Get-FileHash (Join-Path $ProjectRoot 'backtests\europe-market-v1\predictions.csv') -Algorithm SHA256).Hash.ToLowerInvariant()};Parameters=[ordered]@{ModelWeight=$ModelWeight;MarketWeight=$marketWeight;MinimumExpectedValue=$MinimumExpectedValue;KellyFraction=$KellyFraction;MaxStakeFraction=$MaxStakeFraction;InitialBankroll=100};Leagues=$summaries};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
