param(
 [string[]]$LeagueCodes=@('BRA','JPN','SWE'),[string]$ProjectRoot='',[int]$Window=10,[int]$MinimumOverallHistory=5,[int]$MinimumVenueHistory=3,[double]$VenueWeight=0.5,[double]$HomeAdvantage=1.15,[double]$Rho=-0.12,[string]$OutputName='venue-split-v1'
)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)}
$LeagueCodes=@($LeagueCodes|ForEach-Object{$_-split','}|ForEach-Object{$_.Trim().ToUpperInvariant()}|Where-Object{$_});if($VenueWeight-lt0-or$VenueWeight-gt1){throw 'VenueWeight must be in [0,1]'}
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force;$data=Join-Path $ProjectRoot 'data\standardized';$file=Join-Path $data 'matches_all.csv';if(-not(Test-Path $file)){$file=Join-Path $data 'matches.csv'};$out=Join-Path $ProjectRoot ('backtests\'+$OutputName);New-Item -ItemType Directory -Force -Path $out|Out-Null
$all=@(Import-Csv $file -Encoding UTF8|Where-Object{$_.LeagueCode-in$LeagueCodes-and$_.MatchDate-ne''}|Sort-Object LeagueCode,MatchDate,MatchTime,SourceRow);$pred=[Collections.Generic.List[object]]::new();$summary=[Collections.Generic.List[object]]::new()
function New-TeamStats(){@{GF=[Collections.ArrayList]::new();GA=[Collections.ArrayList]::new();HGF=[Collections.ArrayList]::new();HGA=[Collections.ArrayList]::new();AGF=[Collections.ArrayList]::new();AGA=[Collections.ArrayList]::new()}}
function Blend([Collections.ArrayList]$all,[Collections.ArrayList]$venue,[int]$window,[int]$minVenue,[double]$weight){$base=Get-MeanLast $all $window;if($venue.Count-lt$minVenue){return $base};return (1-$weight)*$base+$weight*(Get-MeanLast $venue $window)}
foreach($league in $LeagueCodes){$rows=@($all|Where-Object{$_.LeagueCode-eq$league});if($rows.Count-eq0){throw "No rows for $league"};$s=@{};$n=0;$correct=0;$brier=0.0;$loss=0.0;$counts=@{H=0;D=0;A=0}
 foreach($r in $rows){$h=$r.HomeTeam;$a=$r.AwayTeam;if(-not$s.ContainsKey($h)){$s[$h]=New-TeamStats};if(-not$s.ContainsKey($a)){$s[$a]=New-TeamStats};$hs=$s[$h];$as=$s[$a]
  if($hs.GF.Count-ge$MinimumOverallHistory-and$as.GF.Count-ge$MinimumOverallHistory){$lh=((Blend $hs.GF $hs.HGF $Window $MinimumVenueHistory $VenueWeight)+(Blend $as.GA $as.AGA $Window $MinimumVenueHistory $VenueWeight))/2*$HomeAdvantage;$la=((Blend $as.GF $as.AGF $Window $MinimumVenueHistory $VenueWeight)+(Blend $hs.GA $hs.HGA $Window $MinimumVenueHistory $VenueWeight))/2;$p=Get-DixonColesPrediction $lh $la $Rho;$m=Get-OutcomeMetrics $p.HomeProbability $p.DrawProbability $p.AwayProbability $r.Result;$n++;if($p.Prediction-eq$r.Result){$correct++};$brier+=$m.Brier;$loss+=$m.LogLoss;$pred.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$league;MatchDate=$r.MatchDate;Result=$r.Result;Prediction=$p.Prediction;PH=$p.HomeProbability;PD=$p.DrawProbability;PA=$p.AwayProbability;LambdaH=$p.HomeLambda;LambdaA=$p.AwayLambda;Brier=$m.Brier;LogLoss=$m.LogLoss;HomeVenueHistory=$hs.HGF.Count;AwayVenueHistory=$as.AGF.Count})}
  $hg=[int]$r.HomeGoals;$ag=[int]$r.AwayGoals;[void]$hs.GF.Add($hg);[void]$hs.GA.Add($ag);[void]$hs.HGF.Add($hg);[void]$hs.HGA.Add($ag);[void]$as.GF.Add($ag);[void]$as.GA.Add($hg);[void]$as.AGF.Add($ag);[void]$as.AGA.Add($hg);$counts[$r.Result]++
 }
 $majority=($counts.Values|Measure-Object -Maximum).Maximum/[double]$rows.Count;$acc=if($n){$correct/$n}else{0};$bs=if($n){$brier/$n}else{0};$ll=if($n){$loss/$n}else{0};$gate=$n-ge500-and$acc-ge($majority+0.02)-and$bs-le0.65-and$ll-le1.10;$summary.Add([pscustomobject]@{LeagueCode=$league;SourceMatches=$rows.Count;Evaluated=$n;Accuracy=$acc;Brier=$bs;LogLoss=$ll;MajorityBaseline=$majority;AccuracyLift=$acc-$majority;GatePassed=$gate})
}
$pred|Export-Csv (Join-Path $out 'predictions.csv') -NoTypeInformation -Encoding UTF8;$artifact=[ordered]@{Model='FootballAI-Poisson-VenueSplit';Version='1.0.0-candidate';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');DataSha256=(Get-FileHash $file -Algorithm SHA256).Hash.ToLowerInvariant();Protocol='docs/BACKTEST_PROTOCOL.md';Parameters=[ordered]@{Window=$Window;MinimumOverallHistory=$MinimumOverallHistory;MinimumVenueHistory=$MinimumVenueHistory;VenueWeight=$VenueWeight;HomeAdvantage=$HomeAdvantage;Rho=$Rho};Leagues=$summary};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
