param([string[]]$LeagueCodes=@('FD_B1','FD_D1','FD_E0','FD_E1','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SC1','FD_SP1','FD_T1'),[string]$ProjectRoot='',[double]$MinimumMovement=0.02)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$LeagueCodes=@($LeagueCodes|ForEach-Object{$_-split','}|ForEach-Object{$_.Trim().ToUpperInvariant()}|Where-Object{$_-ne''})
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force;$data=Join-Path $ProjectRoot 'data\standardized';$out=Join-Path $ProjectRoot 'backtests\market-movement-v1';New-Item -ItemType Directory -Force -Path $out|Out-Null
$open=@{};$close=@{};Import-Csv (Join-Path $data 'markets_extended.csv') -Encoding UTF8|ForEach-Object{if($_.Market-eq'1X2_OPEN'){$open[$_.MatchID]=$_}elseif($_.Market-eq'1X2_CLOSE'){$close[$_.MatchID]=$_}}
$rows=@(Import-Csv (Join-Path $data 'matches_all.csv') -Encoding UTF8|Where-Object{$_.LeagueCode-in$LeagueCodes});$preds=[Collections.Generic.List[object]]::new();$summaries=[Collections.Generic.List[object]]::new()
foreach($league in $LeagueCodes){$leagueRows=@($rows|Where-Object{$_.LeagueCode-eq$league});$returns=[Collections.Generic.List[double]]::new();$profit=0.0;$peak=0.0;$maxDrawdown=0.0;$paired=0;$signalCorrect=0;$openCorrect=0;$closeCorrect=0;$sumMove=0.0;$directions=@{H=0;D=0;A=0}
 foreach($r in $leagueRows){if(-not$open.ContainsKey($r.MatchID)-or-not$close.ContainsKey($r.MatchID)){continue};$o=$open[$r.MatchID];$c=$close[$r.MatchID];$op=Get-DeVigProbabilities ([double]$o.HomeOdds) ([double]$o.DrawOdds) ([double]$o.AwayOdds);$cp=Get-DeVigProbabilities ([double]$c.HomeOdds) ([double]$c.DrawOdds) ([double]$c.AwayOdds);if($null-eq$op-or$null-eq$cp){continue};$paired++
  $moves=@(@('H',($cp.HomeProbability-$op.HomeProbability),[double]$c.HomeOdds),@('D',($cp.DrawProbability-$op.DrawProbability),[double]$c.DrawOdds),@('A',($cp.AwayProbability-$op.AwayProbability),[double]$c.AwayOdds))|Sort-Object{[double]$_[1]}-Descending;$signal=$moves[0][0];$movement=[double]$moves[0][1];if($movement-lt$MinimumMovement){continue};$odds=[double]$moves[0][2];$openPick=if($op.HomeProbability-ge$op.DrawProbability-and$op.HomeProbability-ge$op.AwayProbability){'H'}elseif($op.DrawProbability-ge$op.AwayProbability){'D'}else{'A'};$closePick=if($cp.HomeProbability-ge$cp.DrawProbability-and$cp.HomeProbability-ge$cp.AwayProbability){'H'}elseif($cp.DrawProbability-ge$cp.AwayProbability){'D'}else{'A'};$won=$signal-eq$r.Result;$net=if($won){$odds-1.0}else{-1.0};if($won){$signalCorrect++};if($openPick-eq$r.Result){$openCorrect++};if($closePick-eq$r.Result){$closeCorrect++};$directions[$signal]++;$sumMove+=$movement;$returns.Add($net);$profit+=$net;if($profit-gt$peak){$peak=$profit};$dd=$peak-$profit;if($dd-gt$maxDrawdown){$maxDrawdown=$dd}
  $preds.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$league;MatchDate=$r.MatchDate;Result=$r.Result;OpenPH=$op.HomeProbability;OpenPD=$op.DrawProbability;OpenPA=$op.AwayProbability;ClosePH=$cp.HomeProbability;ClosePD=$cp.DrawProbability;ClosePA=$cp.AwayProbability;Signal=$signal;Movement=$movement;OpenFavorite=$openPick;CloseFavorite=$closePick;CloseOdds=$odds;Won=$won;NetReturn=$net;CumulativeProfit=$profit})}
 $n=$returns.Count;$roi=if($n){$profit/$n}else{0};$accuracy=if($n){$signalCorrect/$n}else{0};$openAcc=if($n){$openCorrect/$n}else{0};$closeAcc=if($n){$closeCorrect/$n}else{0};$ss=0.0;foreach($x in $returns){$ss+=($x-$roi)*($x-$roi)};$se=if($n-gt1){[Math]::Sqrt(($ss/($n-1))/$n)}else{$null};$lower=if($null-ne$se){$roi-1.96*$se}else{$null};$pass=$n-ge500-and$accuracy-ge($openAcc+0.02)-and$roi-gt0-and$null-ne$lower-and$lower-gt0
 $summaries.Add([pscustomobject]@{LeagueCode=$league;SourceMatches=$leagueRows.Count;PairedMarkets=$paired;Signals=$n;HomeSignals=$directions.H;DrawSignals=$directions.D;AwaySignals=$directions.A;AverageMovement=if($n){$sumMove/$n}else{$null};SignalAccuracy=$accuracy;OpenFavoriteAccuracy=$openAcc;CloseFavoriteAccuracy=$closeAcc;AccuracyLiftVsOpen=$accuracy-$openAcc;Profit=$profit;ROI=$roi;ReturnStdError=$se;Lower95=$lower;MaxDrawdown=$maxDrawdown;GatePassed=$pass})}
$preds|Export-Csv (Join-Path $out 'predictions.csv') -NoTypeInformation -Encoding UTF8;$artifact=[ordered]@{Model='FootballAI-Market-Movement';Version='1.0.0-candidate';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');DataSha256=(Get-FileHash (Join-Path $data 'matches_all.csv') -Algorithm SHA256).Hash.ToLowerInvariant();MarketSha256=(Get-FileHash (Join-Path $data 'markets_extended.csv') -Algorithm SHA256).Hash.ToLowerInvariant();Protocol='docs/MARKET_MOVEMENT_PROTOCOL.md';Parameters=[ordered]@{MinimumMovement=$MinimumMovement;Stake=1.0;Settlement='CloseOdds'};Leagues=$summaries};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
