param([string[]]$LeagueCodes=@('FD_B1','FD_D1','FD_E0','FD_E1','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SC1','FD_SP1','FD_T1'),[string]$ProjectRoot='',[double]$MinExpectedValue=0.03,[int]$Window=10,[int]$MinimumHistory=5,[double]$HomeAdvantage=1.15,[double]$Rho=-0.12)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$LeagueCodes=@($LeagueCodes|ForEach-Object{$_-split','}|ForEach-Object{$_.Trim().ToUpperInvariant()}|Where-Object{$_-ne''})
Import-Module (Join-Path $ProjectRoot 'src\FootballAI.psm1') -Force;$data=Join-Path $ProjectRoot 'data\standardized';$out=Join-Path $ProjectRoot 'backtests\asian-v1';New-Item -ItemType Directory -Force -Path $out|Out-Null
$markets=@{};Import-Csv (Join-Path $data 'markets_extended.csv') -Encoding UTF8|Where-Object{$_.Market-eq'ASIAN_HANDICAP_CLOSE'}|ForEach-Object{$markets[$_.MatchID]=$_}
$rowsAll=@(Import-Csv (Join-Path $data 'matches_all.csv') -Encoding UTF8|Where-Object{$_.LeagueCode-in$LeagueCodes}|Sort-Object LeagueCode,MatchDate,MatchTime,SourceRow);$preds=[Collections.Generic.List[object]]::new();$summaries=[Collections.Generic.List[object]]::new()
foreach($league in $LeagueCodes){$rows=@($rowsAll|Where-Object{$_.LeagueCode-eq$league});if($rows.Count-eq0){throw "No matches for $league"};$stats=@{};$returns=[Collections.Generic.List[double]]::new();$profit=0.0;$peak=0.0;$maxDrawdown=0.0;$eligible=0;$skipped=0;$outcomeCounts=@{WIN=0;HALF_WIN=0;PUSH=0;HALF_LOSS=0;LOSS=0}
 foreach($r in $rows){$ht=$r.HomeTeam;$at=$r.AwayTeam;if(-not$stats.ContainsKey($ht)){$stats[$ht]=@{GF=[Collections.ArrayList]::new();GA=[Collections.ArrayList]::new()}};if(-not$stats.ContainsKey($at)){$stats[$at]=@{GF=[Collections.ArrayList]::new();GA=[Collections.ArrayList]::new()}};$hs=$stats[$ht];$as=$stats[$at]
  if($hs.GF.Count-ge$MinimumHistory-and$as.GF.Count-ge$MinimumHistory-and$markets.ContainsKey($r.MatchID)){$eligible++;$m=$markets[$r.MatchID];$lh=((Get-MeanLast $hs.GF $Window)+(Get-MeanLast $as.GA $Window))/2.0*$HomeAdvantage;$la=((Get-MeanLast $as.GF $Window)+(Get-MeanLast $hs.GA $Window))/2.0;$ev=Get-AsianExpectedReturn $lh $la $Rho ([double]$m.Line) ([double]$m.HomeOdds) ([double]$m.AwayOdds);$side=if($ev.HomeExpectedReturn-ge$ev.AwayExpectedReturn){'HOME'}else{'AWAY'};$best=if($side-eq'HOME'){$ev.HomeExpectedReturn}else{$ev.AwayExpectedReturn}
   if($best-ge$MinExpectedValue){$odds=if($side-eq'HOME'){[double]$m.HomeOdds}else{[double]$m.AwayOdds};$settle=Get-AsianSettlement ([int]$r.HomeGoals) ([int]$r.AwayGoals) ([double]$m.Line) $side $odds;$returns.Add($settle.NetReturn);$profit+=$settle.NetReturn;if($profit-gt$peak){$peak=$profit};$dd=$peak-$profit;if($dd-gt$maxDrawdown){$maxDrawdown=$dd};$outcomeCounts[$settle.Outcome]++;$preds.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$league;MatchDate=$r.MatchDate;HomeTeam=$ht;AwayTeam=$at;HomeGoals=$r.HomeGoals;AwayGoals=$r.AwayGoals;HomeLine=$m.Line;HomeOdds=$m.HomeOdds;AwayOdds=$m.AwayOdds;LambdaH=$lh;LambdaA=$la;HomeEV=$ev.HomeExpectedReturn;AwayEV=$ev.AwayExpectedReturn;SelectedSide=$side;SelectedEV=$best;Outcome=$settle.Outcome;NetReturn=$settle.NetReturn;CumulativeProfit=$profit})}else{$skipped++}}
  [void]$hs.GF.Add([int]$r.HomeGoals);[void]$hs.GA.Add([int]$r.AwayGoals);[void]$as.GF.Add([int]$r.AwayGoals);[void]$as.GA.Add([int]$r.HomeGoals)}
 $n=$returns.Count;$roi=if($n){$profit/$n}else{0};$mean=$roi;$ss=0.0;foreach($x in $returns){$ss+=($x-$mean)*($x-$mean)};$se=if($n-gt1){[Math]::Sqrt(($ss/($n-1))/$n)}else{$null};$lower=if($null-ne$se){$mean-1.96*$se}else{$null};$pass=$n-ge500-and$roi-gt0-and$null-ne$lower-and$lower-gt0
 $summaries.Add([pscustomobject]@{LeagueCode=$league;SourceMatches=$rows.Count;Eligible=$eligible;Bets=$n;SkippedByEV=$skipped;Profit=$profit;ROI=$roi;ReturnStdError=$se;Lower95=$lower;MaxDrawdown=$maxDrawdown;Win=$outcomeCounts.WIN;HalfWin=$outcomeCounts.HALF_WIN;Push=$outcomeCounts.PUSH;HalfLoss=$outcomeCounts.HALF_LOSS;Loss=$outcomeCounts.LOSS;GatePassed=$pass})}
$preds|Export-Csv (Join-Path $out 'predictions.csv') -NoTypeInformation -Encoding UTF8;$artifact=[ordered]@{Model='FootballAI-Asian-Baseline';Version='1.0.0-candidate';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');DataSha256=(Get-FileHash (Join-Path $data 'matches_all.csv') -Algorithm SHA256).Hash.ToLowerInvariant();MarketSha256=(Get-FileHash (Join-Path $data 'markets_extended.csv') -Algorithm SHA256).Hash.ToLowerInvariant();Protocol='docs/ASIAN_BACKTEST_PROTOCOL.md';Parameters=[ordered]@{MinExpectedValue=$MinExpectedValue;Window=$Window;MinimumHistory=$MinimumHistory;HomeAdvantage=$HomeAdvantage;Rho=$Rho;Stake=1.0};Leagues=$summaries};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
