param([string]$ProjectRoot='')
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$out=Join-Path $ProjectRoot 'backtests\score-calibration-v1';New-Item -ItemType Directory -Force -Path $out|Out-Null
$validated=@('JPN','SWE','FD_B1','FD_D1','FD_E0','FD_F1','FD_G1','FD_I1','FD_N1','FD_P1','FD_SC0','FD_SP1','FD_T1');$raw=@();$raw+=Import-Csv (Join-Path $ProjectRoot 'backtests\baseline-v1\predictions.csv') -Encoding UTF8;$raw+=Import-Csv (Join-Path $ProjectRoot 'backtests\europe-market-v1\predictions.csv') -Encoding UTF8;$rows=[Collections.Generic.List[object]]::new()
function Auc($items,[string]$scoreField,[string]$actualField){$sorted=@($items|Sort-Object{[double]$_.$scoreField});$pos=@($sorted|Where-Object{$_.$actualField-eq'True'}).Count;$neg=$sorted.Count-$pos;if($pos-eq0-or$neg-eq0){return $null};$rank=1;$rankSum=0.0;$i=0;while($i-lt$sorted.Count){$j=$i;$v=[double]$sorted[$i].$scoreField;while($j+1-lt$sorted.Count-and[Math]::Abs(([double]$sorted[$j+1].$scoreField)-$v)-lt1e-12){$j++};$avg=(($i+1)+($j+1))/2.0;for($k=$i;$k-le$j;$k++){if($sorted[$k].$actualField-eq'True'){$rankSum+=$avg}};$i=$j+1};return($rankSum-$pos*($pos+1)/2.0)/($pos*$neg)}
function Metrics($items){$n=$items.Count;$correct=@($items|Where-Object{$_.Correct-eq'True'}).Count;$upsets=@($items|Where-Object{$_.ActualUpset-eq'True'}).Count;$acc=$correct/[double]$n;$ur=$upsets/[double]$n;$aiB=0.0;$upB=0.0;foreach($x in $items){$yc=if($x.Correct-eq'True'){1.0}else{0.0};$yu=if($x.ActualUpset-eq'True'){1.0}else{0.0};$aiB+=(([double]$x.AIScore/100-$yc)*([double]$x.AIScore/100-$yc));$upB+=(([double]$x.UpsetIndex/100-$yu)*([double]$x.UpsetIndex/100-$yu))};$aiB/=$n;$upB/=$n
 $aiE=0.0;$upE=0.0;foreach($b in 0..9){$bin=@($items|Where-Object{[Math]::Min(9,[Math]::Floor([double]$_.AIScore/10))-eq$b});if($bin.Count){$conf=($bin|Measure-Object AIScore -Average).Average/100;$obs=@($bin|Where-Object{$_.Correct-eq'True'}).Count/[double]$bin.Count;$aiE+=$bin.Count/[double]$n*[Math]::Abs($conf-$obs)};$ubin=@($items|Where-Object{[Math]::Min(9,[Math]::Floor([double]$_.UpsetIndex/10))-eq$b});if($ubin.Count){$conf=($ubin|Measure-Object UpsetIndex -Average).Average/100;$obs=@($ubin|Where-Object{$_.ActualUpset-eq'True'}).Count/[double]$ubin.Count;$upE+=$ubin.Count/[double]$n*[Math]::Abs($conf-$obs)}}
 $topN=[Math]::Ceiling($n*0.25);$topAI=@($items|Sort-Object AIScore -Descending|Select-Object -First $topN);$topConf=@($items|Sort-Object Confidence -Descending|Select-Object -First $topN);$topAIAcc=@($topAI|Where-Object{$_.Correct-eq'True'}).Count/[double]$topAI.Count;$topConfAcc=@($topConf|Where-Object{$_.Correct-eq'True'}).Count/[double]$topConf.Count
 return [pscustomobject]@{N=$n;Accuracy=$acc;UpsetRate=$ur;AIBrier=$aiB;AIBaseBrier=$acc*(1-$acc);AIECE=$aiE;AITopQuartileAccuracy=$topAIAcc;AITopLift=$topAIAcc-$acc;ConfidenceAUC=Auc $items 'Confidence' 'Correct';ConfidenceTopQuartileAccuracy=$topConfAcc;ConfidenceTopLift=$topConfAcc-$acc;UpsetBrier=$upB;UpsetBaseBrier=$ur*(1-$ur);UpsetECE=$upE;UpsetAUC=Auc $items 'UpsetIndex' 'ActualUpset'}}
foreach($r in $raw){if($r.LeagueCode-notin$validated-or$r.MarketPH-eq''){continue};$probs=@(@('H',[double]$r.PH),@('D',[double]$r.PD),@('A',[double]$r.PA))|Sort-Object{[double]$_[1]}-Descending;$market=@(@('H',[double]$r.MarketPH),@('D',[double]$r.MarketPD),@('A',[double]$r.MarketPA))|Sort-Object{[double]$_[1]}-Descending;$modelPick=$probs[0][0];$top=[double]$probs[0][1];$second=[double]$probs[1][1];$favorite=$market[0][0];$favoriteModel=if($favorite-eq'H'){[double]$r.PH}elseif($favorite-eq'D'){[double]$r.PD}else{[double]$r.PA};$rows.Add([pscustomobject]@{MatchID=$r.MatchID;LeagueCode=$r.LeagueCode;Result=$r.Result;ModelPick=$modelPick;MarketFavorite=$favorite;Correct=($modelPick-eq$r.Result);ActualUpset=($favorite-ne$r.Result);AIScore=$top*100;Confidence=[Math]::Min(100,($top-$second)*200);UpsetIndex=(1-$favoriteModel)*100})}
$rows|Export-Csv (Join-Path $out 'scores.csv') -NoTypeInformation -Encoding UTF8;$overall=Metrics @($rows);$leagues=[Collections.Generic.List[object]]::new();foreach($league in $validated){$m=Metrics @($rows|Where-Object{$_.LeagueCode-eq$league});$leagues.Add([pscustomobject]@{LeagueCode=$league;N=$m.N;Accuracy=$m.Accuracy;AIBrier=$m.AIBrier;AIBaseBrier=$m.AIBaseBrier;AIECE=$m.AIECE;AITopLift=$m.AITopLift;ConfidenceAUC=$m.ConfidenceAUC;ConfidenceTopLift=$m.ConfidenceTopLift;UpsetRate=$m.UpsetRate;UpsetBrier=$m.UpsetBrier;UpsetBaseBrier=$m.UpsetBaseBrier;UpsetECE=$m.UpsetECE;UpsetAUC=$m.UpsetAUC})}
$aiLeaguePass=@($leagues|Where-Object{$_.AIECE-le0.08-and$_.AIBrier-lt$_.AIBaseBrier}).Count;$confLeaguePass=@($leagues|Where-Object{$_.ConfidenceAUC-ge0.52-and$_.ConfidenceTopLift-gt0}).Count;$upLeaguePass=@($leagues|Where-Object{$_.UpsetAUC-ge0.52-and$_.UpsetBrier-lt$_.UpsetBaseBrier}).Count;$aiPass=$overall.N-ge5000-and$overall.AIECE-le0.05-and$overall.AIBrier-lt$overall.AIBaseBrier-and$overall.AITopLift-ge0.03-and$aiLeaguePass-ge10;$confPass=$overall.ConfidenceAUC-ge0.55-and$overall.ConfidenceTopLift-ge0.03-and$confLeaguePass-ge10;$upPass=$overall.UpsetAUC-ge0.55-and$overall.UpsetECE-le0.05-and$overall.UpsetBrier-lt$overall.UpsetBaseBrier-and$upLeaguePass-ge10
$artifact=[ordered]@{Version='1.0.0';CreatedAt=(Get-Date).ToUniversalTime().ToString('o');Protocol='docs/SCORE_CALIBRATION_PROTOCOL.md';SourcePredictionHashes=@{Baseline=(Get-FileHash (Join-Path $ProjectRoot 'backtests\baseline-v1\predictions.csv') -Algorithm SHA256).Hash.ToLowerInvariant();Europe=(Get-FileHash (Join-Path $ProjectRoot 'backtests\europe-market-v1\predictions.csv') -Algorithm SHA256).Hash.ToLowerInvariant()};Overall=$overall;LeaguePassCounts=@{AIScore=$aiLeaguePass;Confidence=$confLeaguePass;Upset=$upLeaguePass;Required=10};GatePassed=@{AIScore=$aiPass;Confidence=$confPass;Upset=$upPass};Leagues=$leagues};$artifact|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8;$artifact|ConvertTo-Json -Depth 8
