param([string]$ProjectRoot='')
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)}
$archive=Join-Path $ProjectRoot 'data\source_archive\2026-07-15';$inventory=Join-Path $ProjectRoot 'data\source_archive\market_dataset_unique_hashes.csv';$out=Join-Path $ProjectRoot 'data\standardized'
if(-not(Test-Path $inventory)){throw 'Unique-hash inventory is missing'}
$divMap=@{
 'B1'=@('Belgium','Belgian First Division A');'D1'=@('Germany','Bundesliga');'E0'=@('England','Premier League');'E1'=@('England','Championship');
 'F1'=@('France','Ligue 1');'G1'=@('Greece','Super League Greece');'I1'=@('Italy','Serie A');'N1'=@('Netherlands','Eredivisie');
 'P1'=@('Portugal','Primeira Liga');'SC0'=@('Scotland','Premiership');'SC1'=@('Scotland','Championship');'SP1'=@('Spain','La Liga');'T1'=@('Turkey','Super Lig')
}
function ParseDate([string]$value){foreach($f in @('dd/MM/yyyy','dd/MM/yy','d/M/yyyy','d/M/yy')){$d=[datetime]::MinValue;if([datetime]::TryParseExact($value,$f,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::None,[ref]$d)){return $d}};throw "Bad date: $value"}
function Season([datetime]$d){$start=if($d.Month-ge7){$d.Year}else{$d.Year-1};return $start.ToString()+'-'+(($start+1)%100).ToString('00')}
$sha=[Security.Cryptography.SHA256]::Create();function Id([string]$x){$b=[Text.Encoding]::UTF8.GetBytes($x.ToUpperInvariant());$h=[BitConverter]::ToString($sha.ComputeHash($b)).Replace('-','').ToLowerInvariant();return ('FAI-'+$h.Substring(0,24))}
function Num([object]$v){$x=0.0;if([double]::TryParse(([string]$v),[Globalization.NumberStyles]::Float,[Globalization.CultureInfo]::InvariantCulture,[ref]$x)){return $x};return $null}
function AddMarket($list,$id,$source,$row,$market,$provider,$line,$h,$d,$a){$hv=Num $h;$dv=Num $d;$av=Num $a;if($market-like'1X2*'){if($null-ne$hv-and$null-ne$dv-and$null-ne$av-and$hv-gt1-and$dv-gt1-and$av-gt1){$list.Add([pscustomobject]@{MatchID=$id;Market=$market;Provider=$provider;Line='';HomeOdds=$hv;DrawOdds=$dv;AwayOdds=$av;OverOdds='';UnderOdds='';SourceFile=$source;SourceRow=$row})}}elseif($market-like'TOTAL*'){if($null-ne$hv-and$null-ne$av-and$hv-gt1-and$av-gt1){$list.Add([pscustomobject]@{MatchID=$id;Market=$market;Provider=$provider;Line=$line;HomeOdds='';DrawOdds='';AwayOdds='';OverOdds=$hv;UnderOdds=$av;SourceFile=$source;SourceRow=$row})}}else{if($null-ne$line-and$null-ne$hv-and$null-ne$av-and$hv-gt1-and$av-gt1){$list.Add([pscustomobject]@{MatchID=$id;Market=$market;Provider=$provider;Line=$line;HomeOdds=$hv;DrawOdds='';AwayOdds=$av;OverOdds='';UnderOdds='';SourceFile=$source;SourceRow=$row})}}}
$matches=[Collections.Generic.List[object]]::new();$markets=[Collections.Generic.List[object]]::new();$rejects=[Collections.Generic.List[object]]::new();$ids=@{};$sourceFiles=0
foreach($entry in Import-Csv $inventory -Encoding UTF8){$file=$entry.Representative;$path=Join-Path $archive $file;$rows=@(Import-Csv $path -Encoding UTF8);$sourceFiles++
 for($i=0;$i-lt$rows.Count;$i++){$r=$rows[$i];$rowNo=$i+1;$div=([string]$r.Div).Trim();if(-not$divMap.ContainsKey($div)){throw "Unknown Div $div in $file"};$date=ParseDate ([string]$r.Date);$season=Season $date;$homeTeam=([string]$r.HomeTeam).Trim();$awayTeam=([string]$r.AwayTeam).Trim();$hg=0;$ag=0
  if(-not[int]::TryParse(([string]$r.FTHG),[ref]$hg)-or-not[int]::TryParse(([string]$r.FTAG),[ref]$ag)){$rejects.Add([pscustomobject]@{SourceFile=$file;SourceRow=$rowNo;Reason='MISSING_SCORE'});continue};$res=([string]$r.FTR).Trim().ToUpperInvariant();$expected=if($hg-gt$ag){'H'}elseif($hg-eq$ag){'D'}else{'A'};if($res-ne$expected){$rejects.Add([pscustomobject]@{SourceFile=$file;SourceRow=$rowNo;Reason='RESULT_MISMATCH'});continue}
  $code='FD_'+$div;$identity=@($code,$season,$date.ToString('yyyy-MM-dd'),'',$homeTeam,$awayTeam)-join'|';$id=Id $identity;if($ids.ContainsKey($id)){throw "Duplicate archive MatchID $id"};$ids[$id]=$true;$matches.Add([pscustomobject]@{MatchID=$id;Country=$divMap[$div][0];LeagueCode=$code;League=$divMap[$div][1];Season=$season;MatchDate=$date.ToString('yyyy-MM-dd');MatchTime=([string]$r.Time).Trim();Stage='';HomeTeam=$homeTeam;AwayTeam=$awayTeam;HomeGoals=$hg;AwayGoals=$ag;Result=$res;SourceFile=$file;SourceRow=$rowNo})
  AddMarket $markets $id $file $rowNo '1X2_OPEN' 'MarketAverage' '' $r.AvgH $r.AvgD $r.AvgA;AddMarket $markets $id $file $rowNo '1X2_CLOSE' 'MarketAverage' '' $r.AvgCH $r.AvgCD $r.AvgCA
  AddMarket $markets $id $file $rowNo 'TOTAL_OPEN' 'MarketAverage' 2.5 $r.'Avg>2.5' '' $r.'Avg<2.5';AddMarket $markets $id $file $rowNo 'TOTAL_CLOSE' 'MarketAverage' 2.5 $r.'AvgC>2.5' '' $r.'AvgC<2.5'
  AddMarket $markets $id $file $rowNo 'ASIAN_HANDICAP_OPEN' 'MarketAverage' (Num $r.AHh) $r.AvgAHH '' $r.AvgAHA;AddMarket $markets $id $file $rowNo 'ASIAN_HANDICAP_CLOSE' 'MarketAverage' (Num $r.AHCh) $r.AvgCAHH '' $r.AvgCAHA
 }}
$sha.Dispose();$matches|Export-Csv (Join-Path $out 'archive_market_matches.csv') -NoTypeInformation -Encoding UTF8;$markets|Export-Csv (Join-Path $out 'markets_extended.csv') -NoTypeInformation -Encoding UTF8;$rejects|Export-Csv (Join-Path $out 'archive_market_rejected.csv') -NoTypeInformation -Encoding UTF8
$base=@(Import-Csv (Join-Path $out 'matches.csv') -Encoding UTF8);$baseIds=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($r in $base){[void]$baseIds.Add($r.MatchID)};foreach($r in $matches){if(-not$baseIds.Add($r.MatchID)){throw "Cross-source MatchID collision $($r.MatchID)"}};@($base)+@($matches)|Export-Csv (Join-Path $out 'matches_all.csv') -NoTypeInformation -Encoding UTF8
[pscustomobject]@{UniqueSourceFiles=$sourceFiles;ArchiveMatches=$matches.Count;ArchiveMarkets=$markets.Count;Rejected=$rejects.Count;UnifiedMatches=($base.Count+$matches.Count);UniqueUnifiedMatchIDs=$baseIds.Count}|ConvertTo-Json
