Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Get-HmPoisson([double]$Lambda,[int]$MaxGoals=8){$p=New-Object double[] ($MaxGoals+1);$p[0]=[Math]::Exp(-$Lambda);for($k=1;$k-le$MaxGoals;$k++){$p[$k]=$p[$k-1]*$Lambda/$k};return $p}
function Get-JczqHandicapSettlement {param([int]$HomeGoals,[int]$AwayGoals,[int]$HomeHandicap)$adjusted=$HomeGoals+$HomeHandicap;$outcome=if($adjusted-gt$AwayGoals){'H'}elseif($adjusted-eq$AwayGoals){'D'}else{'A'};[pscustomobject]@{HomeGoals=$HomeGoals;AwayGoals=$AwayGoals;HomeHandicap=$HomeHandicap;AdjustedHomeGoals=$adjusted;Outcome=$outcome}}
function Get-JczqHandicapPrediction {
 param([double]$HomeLambda,[double]$AwayLambda,[int]$HomeHandicap,[double]$Rho=-0.12,[int]$MaxGoals=8)
 $hp=Get-HmPoisson ([Math]::Max(.15,[Math]::Min(4.5,$HomeLambda))) $MaxGoals;$ap=Get-HmPoisson ([Math]::Max(.15,[Math]::Min(4.5,$AwayLambda))) $MaxGoals;$sum=0.0;$h=0.0;$d=0.0;$a=0.0;$m=@{w1=0.0;w2=0.0;w3=0.0;draw=0.0;l1=0.0;l2=0.0;l3=0.0}
 for($i=0;$i-le$MaxGoals;$i++){for($j=0;$j-le$MaxGoals;$j++){$tau=1.0;if($i-eq0-and$j-eq0){$tau=1-$HomeLambda*$AwayLambda*$Rho}elseif($i-eq0-and$j-eq1){$tau=1+$HomeLambda*$Rho}elseif($i-eq1-and$j-eq0){$tau=1+$AwayLambda*$Rho}elseif($i-eq1-and$j-eq1){$tau=1-$Rho};$v=[Math]::Max(0.0,$hp[$i]*$ap[$j]*$tau);$sum+=$v;$g=$i-$j;if($g-eq1){$m.w1+=$v}elseif($g-eq2){$m.w2+=$v}elseif($g-ge3){$m.w3+=$v}elseif($g-eq0){$m.draw+=$v}elseif($g-eq-1){$m.l1+=$v}elseif($g-eq-2){$m.l2+=$v}else{$m.l3+=$v};$o=(Get-JczqHandicapSettlement $i $j $HomeHandicap).Outcome;if($o-eq'H'){$h+=$v}elseif($o-eq'D'){$d+=$v}else{$a+=$v}}}
 $b=@([pscustomobject]@{N='HOME_WIN_1';P=$m.w1/$sum},[pscustomobject]@{N='HOME_WIN_2';P=$m.w2/$sum},[pscustomobject]@{N='HOME_WIN_3PLUS';P=$m.w3/$sum},[pscustomobject]@{N='DRAW';P=$m.draw/$sum},[pscustomobject]@{N='AWAY_WIN';P=(($m.l1+$m.l2+$m.l3)/$sum)}|Sort-Object P -Descending)
 [pscustomobject]@{HomeLambda=$HomeLambda;AwayLambda=$AwayLambda;HomeHandicap=$HomeHandicap;HomeWin1Probability=$m.w1/$sum;HomeWin2Probability=$m.w2/$sum;HomeWin3PlusProbability=$m.w3/$sum;DrawProbability=$m.draw/$sum;AwayWinProbability=(($m.l1+$m.l2+$m.l3)/$sum);HandicapWinProbability=$h/$sum;HandicapDrawProbability=$d/$sum;HandicapLossProbability=$a/$sum;TopMarginBucket=$b[0].N;TopMarginProbability=$b[0].P;SecondMarginProbability=$b[1].P}
}
function Get-HandicapMarketProbabilities {param([double]$HandicapWinOdds,[double]$HandicapDrawOdds,[double]$HandicapLossOdds)if($HandicapWinOdds-le1-or$HandicapDrawOdds-le1-or$HandicapLossOdds-le1){return $null};$h=1/$HandicapWinOdds;$d=1/$HandicapDrawOdds;$a=1/$HandicapLossOdds;$s=$h+$d+$a;[pscustomobject]@{HandicapWinProbability=$h/$s;HandicapDrawProbability=$d/$s;HandicapLossProbability=$a/$s;ReturnRate=1/$s}}
function Get-HandicapDecision {param($Prediction,$Market,[int]$SampleSize,[bool]$DataComplete=$true,[bool]$MarketConflict=$false,[bool]$HistoricalGatePassed=$false,[double]$MinimumEdge=.03,[double]$MinimumMarginProbability=.30,[double]$MinimumMarginSeparation=.05,[int]$MinimumSampleSize=80)$model=@{H=$Prediction.HandicapWinProbability;D=$Prediction.HandicapDrawProbability;A=$Prediction.HandicapLossProbability};$mkt=@{H=$Market.HandicapWinProbability;D=$Market.HandicapDrawProbability;A=$Market.HandicapLossProbability};$selected=@('H','D','A')|Sort-Object {$model[$_]-$mkt[$_]} -Descending|Select-Object -First 1;$edge=$model[$selected]-$mkt[$selected];$r=[Collections.Generic.List[string]]::new();if(-not$DataComplete){$r.Add('INCOMPLETE_DATA')};if($SampleSize-lt$MinimumSampleSize){$r.Add('INSUFFICIENT_HISTORY')};if($MarketConflict){$r.Add('MARKET_CONFLICT')};if($Prediction.TopMarginProbability-lt$MinimumMarginProbability){$r.Add('UNCLEAR_GOAL_MARGIN_DISTRIBUTION')};if(($Prediction.TopMarginProbability-$Prediction.SecondMarginProbability)-lt$MinimumMarginSeparation){$r.Add('LOW_GOAL_MARGIN_SEPARATION')};if($edge-lt$MinimumEdge){$r.Add('INSUFFICIENT_EDGE')};if(-not$HistoricalGatePassed){$r.Add('HISTORICAL_HANDICAP_GATE_NOT_PASSED')};[pscustomobject]@{HANDICAP_DECISION=if($r.Count){'SKIP'}else{'SELECT_'+$selected};SelectedOutcome=$selected;ModelProbability=$model[$selected];MarketImpliedProbability=$mkt[$selected];Edge=$edge;Confidence=[Math]::Round([Math]::Max(0,[Math]::Min(100,(($Prediction.TopMarginProbability-$Prediction.SecondMarginProbability)*100+$edge*200))),1);TriggeredReasons=if($r.Count){@()}else{@('EDGE_AND_GATES_PASSED')};RejectedReasons=@($r);FormalRecommendation=$false}}
function Get-HandicapPostMatchAudit {param($Forecast,[int]$HomeGoals,[int]$AwayGoals)$actual=(Get-JczqHandicapSettlement $HomeGoals $AwayGoals ([int]$Forecast.HomeHandicap)).Outcome;$hit=if($Forecast.HANDICAP_DECISION-eq'SKIP'){$null}else{$Forecast.SelectedOutcome-eq$actual};[pscustomobject]@{MatchID=$Forecast.MatchID;LeagueCode=$Forecast.LeagueCode;MatchDate=$Forecast.MatchDate;HomeTeam=$Forecast.HomeTeam;AwayTeam=$Forecast.AwayTeam;HomeHandicap=$Forecast.HomeHandicap;HANDICAP_DECISION=$Forecast.HANDICAP_DECISION;SelectedOutcome=$Forecast.SelectedOutcome;ModelProbability=$Forecast.ModelProbability;MarketImpliedProbability=$Forecast.MarketImpliedProbability;Edge=$Forecast.Edge;Confidence=$Forecast.Confidence;ActualHomeGoals=$HomeGoals;ActualAwayGoals=$AwayGoals;ActualHandicapOutcome=$actual;Hit=$hit;ErrorType=if($Forecast.HANDICAP_DECISION-eq'SKIP'){'SKIPPED'}elseif($hit){'HIT'}else{'GOAL_MARGIN_OR_DIRECTION_MISS'}}}
Export-ModuleMember -Function Get-JczqHandicapSettlement,Get-JczqHandicapPrediction,Get-HandicapMarketProbabilities,Get-HandicapDecision,Get-HandicapPostMatchAudit
